plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
    - 'pkg/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Metrics/ParameterLists:
  Max: 7

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'caml.gemspec'

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 10
